### ISSUE TITLE
getting a global value

### ISSUE THREAD

**Issue by donnaken15** [byxor/NeverScript#57]
I'm trying to do something like this
```
script myloop {
	while {
		i = (printf_calls) // <-- global value i want
		FormatText TextName=text "TEST = %m" m=(<i>)
		SetScreenElementProps id=westext1 text=<text>
		wait 1 gameframe
	}
}
```
but it's just reading it as a QbKey

In an official script source file, a value is apparently retrieved like this:
```
FormatText ChecksumName=color1 "%i_HIGHLIGHTED_TEXT_COLOR" i=(THEME_COLOR_PREFIXES[current_theme_prefix])
color2=(<color1>) // must do this to resolve the global so that I can modify its value locally
```

**Comment by byxor** [comment]
Hi, thanks for your question.

The code looks fine grammatically, but I'm not sure if I understand which part is going wrong.

If `printf_calls` is a numeric type (integer or float), `i = (printf_calls)` should result in the local variable `i` being a numeric type too.

In the past, I used to do things like `i = (1.0 * printf_calls)` to force the expression to be interpreted numerically, but I'm not sure if this is necessary and I try to avoid it now wherever possible.

Give it a go, but my gut tells me that `printf_calls` might not be holding a numeric value (and might be holding a reference to another QbKey or something).

**Comment by donnaken15** [comment]
At the start of my script, I put `printf_calls = 0`
I put the variable in parenthesis and with 1* and it still doesn't show up
I don't know if pre(no pun intended)-THAW has this, but in GH3, I'm able to get a global value by putting an asterisk before the variable name (in a different compiler) (and in hex, an extra byte appears before it)
(post-writing-the-above: It's working now because I disabled/changed code where I try to increment the variable, by doing `i = (printf_calls + 1)` and `change printf_calls = i`, and I just realized I didn't put local brackets around `i` in `change`)
